// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/ad.proto

package ad

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ad) Reset() {
	*x = Ad{}
	mi := &file_proto_ad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ad) ProtoMessage() {}

func (x *Ad) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ad.ProtoReflect.Descriptor instead.
func (*Ad) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{0}
}

func (x *Ad) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ad) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Ad) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Ad) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdRequest) Reset() {
	*x = CreateAdRequest{}
	mi := &file_proto_ad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdRequest) ProtoMessage() {}

func (x *CreateAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdRequest.ProtoReflect.Descriptor instead.
func (*CreateAdRequest) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAdRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAdRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAdRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ad            *Ad                    `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdResponse) Reset() {
	*x = CreateAdResponse{}
	mi := &file_proto_ad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdResponse) ProtoMessage() {}

func (x *CreateAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdResponse.ProtoReflect.Descriptor instead.
func (*CreateAdResponse) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAdResponse) GetAd() *Ad {
	if x != nil {
		return x.Ad
	}
	return nil
}

type GetAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdRequest) Reset() {
	*x = GetAdRequest{}
	mi := &file_proto_ad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdRequest) ProtoMessage() {}

func (x *GetAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdRequest.ProtoReflect.Descriptor instead.
func (*GetAdRequest) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ad            *Ad                    `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdResponse) Reset() {
	*x = GetAdResponse{}
	mi := &file_proto_ad_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdResponse) ProtoMessage() {}

func (x *GetAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdResponse.ProtoReflect.Descriptor instead.
func (*GetAdResponse) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{4}
}

func (x *GetAdResponse) GetAd() *Ad {
	if x != nil {
		return x.Ad
	}
	return nil
}

type ServeAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeAdRequest) Reset() {
	*x = ServeAdRequest{}
	mi := &file_proto_ad_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeAdRequest) ProtoMessage() {}

func (x *ServeAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeAdRequest.ProtoReflect.Descriptor instead.
func (*ServeAdRequest) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{5}
}

func (x *ServeAdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ServeAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeAdResponse) Reset() {
	*x = ServeAdResponse{}
	mi := &file_proto_ad_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeAdResponse) ProtoMessage() {}

func (x *ServeAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeAdResponse.ProtoReflect.Descriptor instead.
func (*ServeAdResponse) Descriptor() ([]byte, []int) {
	return file_proto_ad_proto_rawDescGZIP(), []int{6}
}

func (x *ServeAdResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_proto_ad_proto protoreflect.FileDescriptor

const file_proto_ad_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ad.proto\x12\x02ad\"^\n" +
	"\x02Ad\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"[\n" +
	"\x0fCreateAdRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"*\n" +
	"\x10CreateAdResponse\x12\x16\n" +
	"\x02ad\x18\x01 \x01(\v2\x06.ad.AdR\x02ad\"\x1e\n" +
	"\fGetAdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\rGetAdResponse\x12\x16\n" +
	"\x02ad\x18\x01 \x01(\v2\x06.ad.AdR\x02ad\" \n" +
	"\x0eServeAdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x0fServeAdResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\xa4\x01\n" +
	"\tAdService\x125\n" +
	"\bCreateAd\x12\x13.ad.CreateAdRequest\x1a\x14.ad.CreateAdResponse\x12,\n" +
	"\x05GetAd\x12\x10.ad.GetAdRequest\x1a\x11.ad.GetAdResponse\x122\n" +
	"\aServeAd\x12\x12.ad.ServeAdRequest\x1a\x13.ad.ServeAdResponseB\x13Z\x11adserver/proto/adb\x06proto3"

var (
	file_proto_ad_proto_rawDescOnce sync.Once
	file_proto_ad_proto_rawDescData []byte
)

func file_proto_ad_proto_rawDescGZIP() []byte {
	file_proto_ad_proto_rawDescOnce.Do(func() {
		file_proto_ad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ad_proto_rawDesc), len(file_proto_ad_proto_rawDesc)))
	})
	return file_proto_ad_proto_rawDescData
}

var file_proto_ad_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_ad_proto_goTypes = []any{
	(*Ad)(nil),               // 0: ad.Ad
	(*CreateAdRequest)(nil),  // 1: ad.CreateAdRequest
	(*CreateAdResponse)(nil), // 2: ad.CreateAdResponse
	(*GetAdRequest)(nil),     // 3: ad.GetAdRequest
	(*GetAdResponse)(nil),    // 4: ad.GetAdResponse
	(*ServeAdRequest)(nil),   // 5: ad.ServeAdRequest
	(*ServeAdResponse)(nil),  // 6: ad.ServeAdResponse
}
var file_proto_ad_proto_depIdxs = []int32{
	0, // 0: ad.CreateAdResponse.ad:type_name -> ad.Ad
	0, // 1: ad.GetAdResponse.ad:type_name -> ad.Ad
	1, // 2: ad.AdService.CreateAd:input_type -> ad.CreateAdRequest
	3, // 3: ad.AdService.GetAd:input_type -> ad.GetAdRequest
	5, // 4: ad.AdService.ServeAd:input_type -> ad.ServeAdRequest
	2, // 5: ad.AdService.CreateAd:output_type -> ad.CreateAdResponse
	4, // 6: ad.AdService.GetAd:output_type -> ad.GetAdResponse
	6, // 7: ad.AdService.ServeAd:output_type -> ad.ServeAdResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ad_proto_init() }
func file_proto_ad_proto_init() {
	if File_proto_ad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ad_proto_rawDesc), len(file_proto_ad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ad_proto_goTypes,
		DependencyIndexes: file_proto_ad_proto_depIdxs,
		MessageInfos:      file_proto_ad_proto_msgTypes,
	}.Build()
	File_proto_ad_proto = out.File
	file_proto_ad_proto_goTypes = nil
	file_proto_ad_proto_depIdxs = nil
}
