version: "3.8"

services:
  adserver:
    build:
      context: .
      dockerfile: ./adserver/Dockerfile
    ports:
      - "${ADSERVER_PORT}:${ADSERVER_PORT}"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${ADSERVER_PORT}
      - AD_COLLECTION=${AD_COLLECTION}
      - TRACKER_COLLECTION=${TRACKER_COLLECTION}
    networks:
      - backend

  tracker:
    build:
      context: ./tracker
    ports:
      - "${TRACKER_PORT}:${TRACKER_PORT}"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${ADSERVER_PORT}
      - TRACKER_COLLECTION=${TRACKER_COLLECTION}
    networks:
      - backend

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379"
    networks:
      - backend

  mongo:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

networks:
  backend:

volumes:
  mongo_data:
