version: "3.8"

services:
  tracker:
    build:
      context: ./tracker
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "50052:50052"
    networks:
      - backend
  adserver:
    build: ./adserver
    ports:
      - "50051:50051"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - backend
    volumes:
      - ./tracker:/app/tracker

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379"
    networks:
      - backend

  mongo:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

networks:
  backend:

volumes:
  mongo_data:
