// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: tracker/proto/tracker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackClickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdId          string                 `protobuf:"bytes,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	Count         string                 `protobuf:"bytes,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackClickRequest) Reset() {
	*x = TrackClickRequest{}
	mi := &file_tracker_proto_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackClickRequest) ProtoMessage() {}

func (x *TrackClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackClickRequest.ProtoReflect.Descriptor instead.
func (*TrackClickRequest) Descriptor() ([]byte, []int) {
	return file_tracker_proto_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *TrackClickRequest) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

func (x *TrackClickRequest) GetCount() string {
	if x != nil {
		return x.Count
	}
	return ""
}

type TrackClickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackClickResponse) Reset() {
	*x = TrackClickResponse{}
	mi := &file_tracker_proto_tracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackClickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackClickResponse) ProtoMessage() {}

func (x *TrackClickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_tracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackClickResponse.ProtoReflect.Descriptor instead.
func (*TrackClickResponse) Descriptor() ([]byte, []int) {
	return file_tracker_proto_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *TrackClickResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_tracker_proto_tracker_proto protoreflect.FileDescriptor

const file_tracker_proto_tracker_proto_rawDesc = "" +
	"\n" +
	"\x1btracker/proto/tracker.proto\x12\atracker\">\n" +
	"\x11TrackClickRequest\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\tR\x04adId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\tR\x05count\".\n" +
	"\x12TrackClickResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2W\n" +
	"\x0eTrackerService\x12E\n" +
	"\n" +
	"TrackClick\x12\x1a.tracker.TrackClickRequest\x1a\x1b.tracker.TrackClickResponseB1Z/github.com/Bellzebuth/arago/tracker/proto/protob\x06proto3"

var (
	file_tracker_proto_tracker_proto_rawDescOnce sync.Once
	file_tracker_proto_tracker_proto_rawDescData []byte
)

func file_tracker_proto_tracker_proto_rawDescGZIP() []byte {
	file_tracker_proto_tracker_proto_rawDescOnce.Do(func() {
		file_tracker_proto_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracker_proto_tracker_proto_rawDesc), len(file_tracker_proto_tracker_proto_rawDesc)))
	})
	return file_tracker_proto_tracker_proto_rawDescData
}

var file_tracker_proto_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tracker_proto_tracker_proto_goTypes = []any{
	(*TrackClickRequest)(nil),  // 0: tracker.TrackClickRequest
	(*TrackClickResponse)(nil), // 1: tracker.TrackClickResponse
}
var file_tracker_proto_tracker_proto_depIdxs = []int32{
	0, // 0: tracker.TrackerService.TrackClick:input_type -> tracker.TrackClickRequest
	1, // 1: tracker.TrackerService.TrackClick:output_type -> tracker.TrackClickResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tracker_proto_tracker_proto_init() }
func file_tracker_proto_tracker_proto_init() {
	if File_tracker_proto_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracker_proto_tracker_proto_rawDesc), len(file_tracker_proto_tracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracker_proto_tracker_proto_goTypes,
		DependencyIndexes: file_tracker_proto_tracker_proto_depIdxs,
		MessageInfos:      file_tracker_proto_tracker_proto_msgTypes,
	}.Build()
	File_tracker_proto_tracker_proto = out.File
	file_tracker_proto_tracker_proto_goTypes = nil
	file_tracker_proto_tracker_proto_depIdxs = nil
}
